# Generated by Django 4.2.7 on 2026-07-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField(default=0.0)),
                ("humidity", models.FloatField(default=0.0)),
                ("soil", models.IntegerField(default=0)),
                ("gas", models.IntegerField(default=0)),
                ("ldr", models.IntegerField(default=0)),
                ("fan", models.BooleanField(default=False)),
                ("pump", models.BooleanField(default=False)),
                ("heater", models.BooleanField(default=False)),
                ("alarm", models.BooleanField(default=False)),
                ("light", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
