# Generated by Django 4.2.7 on 2026-07-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("embedded", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "اطلاعات"),
                            ("warning", "هشدار"),
                            ("critical", "خطرناک"),
                            ("success", "موفقیت"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("temp_high", "دمای بالا"),
                            ("temp_low", "دمای پایین"),
                            ("temp_normal", "دمای نرمال"),
                            ("hum_high", "رطوبت بالا"),
                            ("hum_low", "رطوبت پایین"),
                            ("hum_normal", "رطوبت نرمال"),
                            ("soil_dry", "خاک خشک"),
                            ("soil_wet", "خاک مرطوب"),
                            ("gas_danger", "گاز خطرناک"),
                            ("gas_normal", "گاز نرمال"),
                            ("light_low", "نور ناکافی"),
                            ("light_normal", "نور نرمال"),
                            ("pump_on", "پمپ روشن شد"),
                            ("pump_off", "پمپ خاموش شد"),
                            ("fan_on", "فن روشن شد"),
                            ("fan_off", "فن خاموش شد"),
                            ("light_on", "نور مصنوعی روشن شد"),
                            ("light_off", "نور مصنوعی خاموش شد"),
                            ("heater_on", "گرمایش روشن شد"),
                            ("heater_off", "گرمایش خاموش شد"),
                            ("alarm_on", "آلارم فعال شد"),
                            ("alarm_off", "آلارم غیرفعال شد"),
                            ("device_online", "دستگاه آنلاین شد"),
                            ("device_offline", "دستگاه آفلاین شد"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("sensor_data", models.JSONField(blank=True, default=dict)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("seen", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["created", "seen"],
                        name="embedded_sy_created_c5d2e9_idx",
                    )
                ],
            },
        ),
    ]
