# Generated by Django 4.2.7 on 2026-07-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("embedded", "0002_systemevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActuatorState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pump", models.BooleanField(default=False)),
                ("light", models.BooleanField(default=False)),
                ("fan", models.BooleanField(default=False)),
                ("alarm", models.BooleanField(default=False)),
                ("heater", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
