# Generated by Django 4.2.7 on 2026-07-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("embedded", "0003_actuatorstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="auto",
            field=models.BooleanField(default=True),
        ),
    ]
